name: base
description: "Base package"
version: 1.0.1
publish_to: none

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # State Management
  get: ^4.6.6

  # API & Utils
  dio: ^5.4.3+1
  basic_utils: ^5.6.1

  # Date Handling (Jiffy diganti karena konflik dengan intl)
  timeago: ^3.6.0 # Alternatif yang lebih ringan dan kompatibel

  # Preferences
  shared_preferences: ^2.2.2

  # UI Components
  flutter_date_pickers: ^0.4.1
  lottie: ^3.1.2
  easy_localization: ^3.0.5
  photo_view: ^0.14.0
  video_player: ^2.8.6
  mask_text_input_formatter: ^2.7.0
  file_picker: ^8.1.4
  image_picker: ^1.0.7
  smooth_corner: ^1.1.1
  dotted_border: ^2.1.0

  # Camera & Compression
  camera: ^0.10.5+9
  flutter_image_compress: ^2.2.0

  # Timer & Countdown
  timer_count_down: ^2.2.2

  # Location
  detect_fake_location: ^2.1.0
  geolocator: ^11.0.0
  collection: ^1.19.1 # Sesuai dengan dependensi SDK
  syncfusion_flutter_datepicker: ^30.1.38

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
